### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::8084

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#897]
## Description
Unable to run the project using instructions from the README. I've also tried with Volta. When running `npm run storybook`, I get the following error:

```
Error: listen EADDRINUSE: address already in use :::8084
```
<details>
<summary>
Console error message
</summary>

```
lerna ERR! npm run storybook exited 1 in '@creativecommons/vue-vocabulary'
lerna ERR! npm run storybook stdout:

> @creativecommons/vue-vocabulary@2020.11.3 storybook /home/cc/Code/vocabulary/packages/vue-vocabulary
> vue-cli-service storybook:serve --ci -s ./src/assets -p 8082

lerna ERR! npm run storybook stderr:
info @storybook/vue v6.2.9
info 
info => Loading presets
info => Serving static files from ././src/assets at /
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8084
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at /home/cc/Code/vocabulary/packages/vue-vocabulary/node_modules/@storybook/core-server/dist/cjs/dev-server.js:78:12
    at new Promise (<anonymous>)
    at storybookDevServer (/home/cc/Code/vocabulary/packages/vue-vocabulary/node_modules/@storybook/core-server/dist/cjs/dev-server.js:75:9)
    at async buildDevStandalone (/home/cc/Code/vocabulary/packages/vue-vocabulary/node_modules/@storybook/core-server/dist/cjs/build-dev.js:107:31)
    at async Object.buildDev (/home/cc/Code/vocabulary/packages/vue-vocabulary/node_modules/@storybook/core-server/dist/cjs/build-dev.js:147:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8084
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @creativecommons/vue-vocabulary@2020.11.3 storybook: `vue-cli-service storybook:serve --ci -s ./src/assets -p 8082`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @creativecommons/vue-vocabulary@2020.11.3 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cc/.npm/_logs/2021-06-09T10_10_14_741Z-debug.log
```

</details>

<details>
<summary>
Full debug log
</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/cc/.volta/tools/image/node/14.15.1/bin/node',
1 verbose cli   '/home/cc/.volta/tools/image/npm/6.14.9/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'storybook'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.1
4 verbose run-script [ 'prestorybook', 'storybook', 'poststorybook' ]
5 info lifecycle root@~prestorybook: root@
6 info lifecycle root@~storybook: root@
7 verbose lifecycle root@~storybook: unsafe-perm in lifecycle true
8 verbose lifecycle root@~storybook: PATH: /home/cc/.volta/tools/image/npm/6.14.9/node_modules/npm-lifecycle/node-gyp-bin:/home/cc/Code/vocabulary/node_modules/.bin:/home/cc/.volta/tools/image/npm/6.14.9/bin:/home/cc/.volta/tools/image/node/14.15.1/bin:/home/cc/.volta/bin:/home/cc/.nvm/versions/node/v12.22.1/bin:/home/cc/.pyenv/bin:/home/cc/.local/bin:/home/cc/.local/bin:/home/cc/.pyenv/bin:/home/cc/.local/bin:/home/cc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle root@~storybook: CWD: /home/cc/Code/vocabulary
10 silly lifecycle root@~storybook: Args: [ '-c', 'lerna run storybook --parallel' ]
11 silly lifecycle root@~storybook: Returned: code: 1  signal: null
12 info lifecycle root@~storybook: Failed to exec storybook script
13 verbose stack Error: root@ storybook: `lerna run storybook --parallel`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/cc/.volta/tools/image/npm/6.14.9/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/cc/.volta/tools/image/npm/6.14.9/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid root@
15 verbose cwd /home/cc/Code/vocabulary
16 verbose Linux 5.4.0-74-generic
17 verbose argv "/home/cc/.volta/tools/image/node/14.15.1/bin/node" "/home/cc/.volta/tools/image/npm/6.14.9/bin/npm-cli.js" "run" "storybook"
18 verbose node v14.15.1
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error root@ storybook: `lerna run storybook --parallel`
22 error Exit status 1
23 error Failed at the root@ storybook script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
</details>

## Reproduction

Run the following steps with or without Volta. If not using Volta, use node 14 and npm 6.

1. clone the repository
2. `npm install --legacy-peer-deps`
3. `npm run setup`
4. `npm run build`
5. `npm run storybook`

## Expectation

The project would run successfully when following instructions in the README on a freshly-cloned repository.

## Environment

 - Device: laptop
 - OS: Ubuntu 20.04
 - Other info: node 14; npm 6; with or without Volta

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I've tried debugging this in several ways, all unsuccessful. Some things I've done:

- Rollback to previous commits where the project was known to work (`git checkout bf17139ce1a7d149f743c798bb6e7a98e1e92380` for example), but the `EADDRINUSE` port errors are still present
- Remove lock files and reinstall dependencies
- Manually roll back storybook and other dependencies to earlier versions

As you've addressed there are several issues with both the build and running storybook.

The only other thing I can think of is that I'm now on an M1 mac, but that seems an unlikely culprit. Do you happen to be using one?

**Comment by brylie** [comment]
I'm running Ubuntu 20.04 on an ASUS tower. I think the underlying issue is complexity

**Comment by zackkrida** [comment]
> underlying issue is complexity

Isn't that the case with any software? I don't think complexity is inherently bad. Doing complex things requires complexity. For this project however, I think your suggestions to simplify are wise, and encouraged. Storybook in particular feels disproportionately heavy and complex in comparison to the value it provides.

Vocabulary could fundamentally be a single CSS file.

**Comment by brylie** [comment]
Yeah, agreed. Our biggest battle as software engineers is with complexity. One of the arts of science and engineering is in reducing complex things down to their essence. :-)

**Comment by brylie** [comment]
One phrase that comes to mind is "proportionate complexity". It's also worth reflecting on ideas like Kanban and Lean that aim to distill things to their essence and make that essence intuitive and visible.

**Comment by brylie** [comment]
By the way, I really appreciate your help in troubleshooting this issue as well as your perspective :smiley:
